M48
; #@! TF.GenerationSoftware,LibrePCB,LibrePCB,1.3.0
; #@! TF.CreationDate,2025-10-25T23:30:35
; #@! TF.ProjectId,GateGuardian - Sommer Twist 350 Swing Gate,8a633c5c-b075-4c35-a81d-aba18a590e16,v1.1
; #@! TF.Part,Single
; #@! TF.SameCoordinates
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC,TZ
; #@! TA.AperFunction,MechanicalDrill
T1C3.0
%
G90
G05
M71
T1
X3.81Y70.1675
X123.825Y13.6525
X43.18Y6.0325
X130.81Y53.0225
X66.675Y51.1175
T0
M30
